### ISSUE TITLE
Definir as funcionalidades do app

### ISSUE THREAD

**Issue by maisamrr** [maisamrr/caronasIESB#1]

**Comment by maisamrr** [comment]
- **Funcionalidades**: Cadastro, login, solicitar carona, oferecer carona, histórico do usuário, avaliações
- 
- Telas:
    - Tela inicial (logo, etc etc)
    - **USUÁRIO**
    - Cadastro de novo usuário
    - Login de usuário
    - Tela de perfil de usuário
    - **CARONA**
    - Tela de caronas disponíveis (principal)
    - Tela de oferecer carona

**Comment by maisamrr** [comment]
https://www.figma.com/file/F2Ul774u7XnDRX82C3vANo/pdm1?node-id=0%3A1&t=CehMCgdOcMSuwRuF-1

**Comment by hungryworld** [comment]
Pensei em algumas funcionalidades já baseadas no progresso do _figma_, sua composição em tópicos e suas respectivas telas no aplicativo:

**1. Log-in (1 tela)**

- endereço de e-mail (institucional)
- senha
- opção de cadastrar-se

**2. Cadastro (2 telas)**

_1º tela_

- nome completo
- endereço de e-mail (institucional)
- número de telefone
- senha _(levemente complexa, com certos requisitos a serem preenchidos)_
- foto de perfil _(possível adição de um aviso de que dificilmente outros usuários aceitarão a interação com você se não possuir uma foto de perfil humana e própria)_
- data de nascimento
- gênero (opcional)

_2º tela_

- o botão de concluir registro só ficaria visível caso o usuário confirmasse que concorda com os _Termos e Condições_ , com a opção de clicando na palavra, permitir que a visualização do mesmo ao gerar uma nova tela.

**3. Solicitação de carona (2 telas)**


_1º tela_

- as caronas mais recentes aparecerão, inicialmente, na tela principal como designado no _figma_
- opção de especificar local de chegada (escolhido pelo usuário utilizando um mini-mapa integrado do Google Maps **OU** inserindo um CEP)
- exibição das caronas disponíveis de acordo com o filtro principal de localidade (haverá um padrão que definirá se está apto ou não, mais a frente na tela de _Oferta de carona_)
- filtros secundários: fumante-friendly, voluntário ou pago, tipo de pagamento (pix ou dinheiro)
- o padrão de exibição de uma carona inclui informações do motorista: {nome, nota, horário de partida/chegada estimado e número de assentos disponíveis)


_2º tela_

- só aparecerá quando o cliente clicar em solicitar carona, ela exibirá detalhes adicionais do motorista como placa do carro, além dos detalhes já exibidos na primeira tela
- o pagamento por pix deverá ser feito aqui (discutir sobre a segurança disso aqui futuramente)
- conclusão da requisição de carona, avisando que o motorista deverá aceitar em até X horas (ou minutos?)

**4. Oferecer carona (3 telas)**

_1º tela_

- só aparecerá na primeira vez, exclusivamente para cadastro, precisará informar:
- placa do carro
- cor do carro
- modelo do carro
- número de assentos disponíveis


_2º tela_

- tela principal de oferecimento, é a que sempre vai aparecer desde que o usuário esteja devidamente cadastrado
- informar rota, horário de partida e limite de quilometragem a partir do destino do motorista (ou seja, se o destino é no CEP X, ele só irá aceitar passageiros que tenham o destino em um raio de até Y km de distância partindo do CEP X)
- botão de postar carona

_3º tela_

- só aparecerá quando a carona por devidamente postada, ela irá atualizar conforme passageiros requisitarem essa carona, mostrando informações básicas sobre os passageiros como nome e nota


**5. Avaliações e feedback (1 tela)**

- após a conclusão da carona, os usuários podem avaliar uns aos outros e fornecer feedback sobre a experiência da carona.

**6. Perfil do usuário (1 tela)**

- possibilidade de editar as seguintes informações:
- nome e sobrenome
- número de telefone
- endereço de e-mail
- senha
_______________________________________
- divisória visível apenas para os que possuem carro cadastrado
- permitir atualizar todos os dados do carro, além da possibilidade de excluir e/ou adicionar um carro


**7. Pontos extras a se pensar**

- notificações
