### ISSUE TITLE
Mockup#11 - perfil do usuário

### ISSUE THREAD

**Issue by maisamrr** [maisamrr/caronasIESB#12]
Possibilidade de editar as seguintes informações.
Elementos:
- Carregar foto de perfil
- Nome
- Curso
- Semestre
- Celular
- E-mail
- Senha

Não é possível alterar a matrícula nem o gênero (usuário deve entrar em contato caso queira fazer essas alterações).

**Comment by hungryworld** [comment]
https://www.figma.com/file/1aulxp0zrPz0fWuqyd5ZW2/pdm1-(Copy)?node-id=0%3A1&t=Jf9LzJ2AQuUeQmVj-1
