### ISSUE TITLE
Mockup#03 - tela home

### ISSUE THREAD

**Issue by maisamrr** [maisamrr/caronasIESB#4]
Tela logo após o login/cadastro confirmado
Elementos:
- Nome da pessoa
- Menu hamburger
- Campo de busca
- Exibição das últimas caronas oferecidas
- Barra no rodapé com Home/Carona/Usuário (ícones)

**Comment by GusPLF0** [comment]
(FEEDBACK PROFESSOR) Fazer alteração no rodapé
