### ISSUE TITLE
Alterações Home

### ISSUE THREAD

**Issue by maisamrr** [maisamrr/caronasIESB#46]
- Quando clicar nos endereços em destaque na Home, preencher automaticamente a tela de Destino com esse endereço
- Trocar o ícone de relógio por uma seta
- No campo "Qual o seu destino", permitir que o usuário digite (depois vamos integrar com API de procurar endereço). Quando estiver preenchido, a setinha fica verde para o usuário confirmar e ir para a tela de Destino

**Rotas**
- Impedir de voltar para a tela de Login assim que for pra essa tela

**Comment by GusPLF0** [comment]
![image](https://github.com/maisamrr/caronasIESB/assets/79981630/9213b182-47c4-4f1e-88db-54c967d2f8cb)
Outra alteração a ser feita na parte de home (Relacionado ao backend)

============================================================================

![image](https://github.com/maisamrr/caronasIESB/assets/79981630/b3d2987c-9527-4224-be97-bb007781ab7d)
Alterações necessárias para permitir que o usuário digite seu endereço e ícone de seta
Possível teremos que fazer o widget ficar statefull para mudar a cor da seta para verde quando o usuário digitar o endereço.

Além disso, acho que o widget tem que ser statefull para quando clicar nos endereços em destaque o campo ser automaticamente preenchido
