### ISSUE TITLE
Mockup#06 - tela oferecer carona COM veículo cadastrado

### ISSUE THREAD

**Issue by maisamrr** [maisamrr/caronasIESB#7]
Elementos:
- Campo para inserir o local de partida
- Campo para inserir o destino
- Campo para inserir o horário de saída
- Campo de limite de quilometragem (o quanto a pessoa aceita se "desviar"da sua rota para pegar alguém)
- Campo para informar quantos assentos disponíveis
- Campo para escolher se a corrida exige pagamento ou se a contribuição é voluntária. Se for obrigatório pagar, informar o valor
- Botão "VemJunto" para postar o oferecimento de carona

**Comment by hungryworld** [comment]
https://www.figma.com/file/1aulxp0zrPz0fWuqyd5ZW2/pdm1-(Copy)?node-id=0%3A1&t=Jf9LzJ2AQuUeQmVj-1

**Comment by maisamrr** [comment]
Ela vai "mesclar"com a tela 05
