### ISSUE TITLE
Mockup#07 - tela de carona postada

### ISSUE THREAD

**Issue by maisamrr** [maisamrr/caronasIESB#8]
Só aparecerá quando a carona por devidamente postada. Irá atualizar conforme passageiros requisitarem essa carona, mostrando informações básicas sobre os passageiros.
Elementos:
- Nome usuário
- Menu hamburger
- Exibição em destaque da carona oferecida (a carona que está em aberto aguardando alguém aceitar)
- Exibição sem destaque das caronas passadas

Pensar em como essa exibição vai ficar quando uma pessoa aceitar a carona. Pensei em aparecer uma notificação em vermelho, para a pessoa clicar e ver os detalhes de quem aceitou, aí ela aprova ou não.

**Comment by FelpsFon** [comment]
Mockup feito na tela "Oferecer carona - com carros cadastrados"
