### ISSUE TITLE
Mockup#08 - carona ativa

### ISSUE THREAD

**Issue by maisamrr** [maisamrr/caronasIESB#9]
Acredito que pode ser a mesma tela para quem solicitou e ofereceu.
Elementos:
- Mapa com a rota em destaque, que vai atualizando em tempo real
- Informações de quem está no carro (fotinhas dos usuários)
- Informações do veículo
- Informações de valor da corrida (caso seja pagamento voluntário, tem que aparecer essa info)
- Horário com previsão de chegada
- Botão para compartilhar a rota com algum contato da pessoa (medida de segurança)
- Botão para cancelar corrida

**Comment by hungryworld** [comment]
https://www.figma.com/file/1aulxp0zrPz0fWuqyd5ZW2/pdm1-(Copy)?node-id=0%3A1&t=Jf9LzJ2AQuUeQmVj-1
